"""Rider-Waite-style 78-card catalog with short Vietnamese meanings."""

from __future__ import annotations

# (number, name_en, name_vi, short_vi, upright, reversed, kw_up, kw_rev)
MAJOR_ARCANA: tuple[tuple[int, str, str, str, str, str, str, str], ...] = (
    (
        0,
        "The Fool",
        "Kẻ Ngốc",
        "Kẻ Ngốc",
        "Khởi đầu mới và một bước nhảy vào điều chưa biết. Hãy tin hành trình.",
        "Bốc đồng hoặc thiếu chuẩn bị. Nhìn lại trước khi lao tới.",
        "khởi đầu, niềm tin",
        "bốc đồng, thiếu chuẩn bị",
    ),
    (
        1,
        "The Magician",
        "Nhà Ảo Thuật",
        "Ảo Thuật",
        "Bạn đang có đủ công cụ để biến ý định thành hiện thực.",
        "Tài năng bị lãng phí, hoặc lời nói đang che một khoảng trống.",
        "ý chí, thể hiện",
        "lãng phí, giả tạo",
    ),
    (
        2,
        "The High Priestess",
        "Nữ Tư Tế",
        "Tư Tế",
        "Lắng nghe trực giác. Câu trả lời đang nằm trong sự im lặng.",
        "Bỏ qua nội tâm; bí mật bị đẩy sang một bên thay vì được đọc.",
        "trực giác, ẩn số",
        "lãng quên, bí mật",
    ),
    (
        3,
        "The Empress",
        "Nữ Hoàng",
        "Nữ Hoàng",
        "Nuôi dưỡng, sung túc và sáng tạo đang nở. Cho phép mọi thứ lớn lên.",
        "Bỏ bê bản thân, hoặc siết quá chặt thứ cần được thở.",
        "nuôi dưỡng, dư dả",
        "bỏ bê, siết chặt",
    ),
    (
        4,
        "The Emperor",
        "Hoàng Đế",
        "Hoàng Đế",
        "Trật tự, kỷ luật và một nền tảng vững. Hãy đứng làm trụ.",
        "Cứng nhắc hoặc kiểm soát quá đà; quyền lực đang đè lên thay vì nâng.",
        "trật tự, trụ cột",
        "cứng nhắc, áp chế",
    ),
    (
        5,
        "The Hierophant",
        "Giáo Hoàng",
        "Giáo Hoàng",
        "Truyền thống, người thầy và con đường đã được mở cho bạn.",
        "Phá lệ và nghi ngờ giáo điều. Lúc này cần chân lý riêng.",
        "truyền thống, chỉ dẫn",
        "phá lệ, tự hỏi",
    ),
    (
        6,
        "The Lovers",
        "Những Người Yêu",
        "Người Yêu",
        "Một lựa chọn bằng tim. Kết nối và sự hòa hợp đang gọi.",
        "Lệch pha, tránh quyết định, hoặc gắn bó vì sợ chứ không vì yêu.",
        "lựa chọn, hòa hợp",
        "lệch pha, do dự",
    ),
    (
        7,
        "The Chariot",
        "Chiến Xa",
        "Chiến Xa",
        "Ý chí thắng thế. Tiến lên khi hai hướng đã được nắm trong một tay lái.",
        "Mất lái, bị kéo về hai phía, hoặc cái tôi đang lấn đường.",
        "ý chí, tiến lên",
        "mất lái, phân tán",
    ),
    (
        8,
        "Strength",
        "Sức Mạnh",
        "Sức Mạnh",
        "Dũng cảm mềm mại. Thuần hóa chứ không đè bẹp.",
        "Tự nghi hoặc nóng giận; sức thô đang thay cho sự dịu.",
        "can đảm, mềm mỏng",
        "nóng giận, tự nghi",
    ),
    (
        9,
        "The Hermit",
        "Ẩn Sĩ",
        "Ẩn Sĩ",
        "Rút vào trong để tìm ánh sáng riêng. Câu trả lời không ở đám đông.",
        "Cô lập quá mức, hoặc sợ một mình nên bám lấy ồn ào.",
        "tĩnh, tìm ánh sáng",
        "cô lập, trốn tránh",
    ),
    (
        10,
        "Wheel of Fortune",
        "Bánh Xe Số Mệnh",
        "Bánh Xe",
        "Vận xoay. Một cửa sổ cơ hội đang mở trong chu kỳ đổi.",
        "Trễ nhịp, kháng cự thay đổi, hoặc đang kẹt vòng lặp cũ.",
        "vận may, chu kỳ",
        "trễ nhịp, kháng cự",
    ),
    (
        11,
        "Justice",
        "Công Lý",
        "Công Lý",
        "Công bằng và nhân quả. Sự thật được cân, hãy chịu phần của mình.",
        "Thiên vị hoặc tránh trách nhiệm; cán cân đang lệch.",
        "công bằng, nhân quả",
        "lệch, thoái thác",
    ),
    (
        12,
        "The Hanged Man",
        "Người Bị Treo",
        "Người Treo",
        "Buông và đổi góc nhìn. Đôi khi chờ đúng lúc chính là hành động.",
        "Hy sinh vô ích, kẹt trong thế treo, hoặc trì hoãn để khỏi chọn.",
        "buông, đổi góc",
        "kẹt, stall",
    ),
    (
        13,
        "Death",
        "Tử Thần",
        "Tử Thần",
        "Một kết thúc cần thiết. Lột xác để cửa khác mở.",
        "Bám lấy cái đã chết, sợ thay đổi, chuyển mình bị trì.",
        "kết thúc, lột xác",
        "bám víu, trì hoãn",
    ),
    (
        14,
        "Temperance",
        "Tiết Chế",
        "Tiết Chế",
        "Trung dung và hòa trộn. Chữa lành từ từ vẫn là chữa lành.",
        "Thái quá, mất kiên nhẫn, các phần không chịu hòa vào nhau.",
        "cân bằng, hòa",
        "thái quá, nôn nóng",
    ),
    (
        15,
        "The Devil",
        "Ác Quỷ",
        "Ác Quỷ",
        "Ràng buộc, dục vọng, một hợp đồng với bóng tối của chính mình.",
        "Cởi xiềng. Nhìn ra sợi xích vốn do mình giữ.",
        "ràng buộc, ham muốn",
        "cởi trói, tỉnh",
    ),
    (
        16,
        "The Tower",
        "Tòa Tháp",
        "Tòa Tháp",
        "Sụp đổ bất ngờ. Sự thật phá tháp ảo để còn lại phần thật.",
        "Trì hoãn sụp đổ; sửa cho khỏi sập thay vì dám xây lại.",
        "sụp đổ, sự thật",
        "trì, vá víu",
    ),
    (
        17,
        "The Star",
        "Ngôi Sao",
        "Ngôi Sao",
        "Hy vọng và chữa lành. Niềm tin đang trở lại sau bão.",
        "Mất niềm tin, hy vọng bị hoãn, tự khép lại trước ánh sáng.",
        "hy vọng, chữa lành",
        "mất tin, khép lại",
    ),
    (
        18,
        "The Moon",
        "Mặt Trăng",
        "Mặt Trăng",
        "Ảo ảnh, giấc mơ và nỗi sợ dưới bề mặt. Đừng tin mỗi thứ bạn thấy.",
        "Sương mù tan. Điều từng bị bóp méo đang hiện ra đúng hình.",
        "ảo ảnh, tiềm thức",
        "sáng tỏ, tỉnh mộng",
    ),
    (
        19,
        "The Sun",
        "Mặt Trời",
        "Mặt Trời",
        "Rõ ràng, vui và thành công không cần giấu. Được phép sáng.",
        "Niềm vui bị che, kiêu hãnh, hoặc thành công đang bị trì.",
        "rõ ràng, vui",
        "che khuất, kiêu",
    ),
    (
        20,
        "Judgement",
        "Phán Xét",
        "Phán Xét",
        "Thức tỉnh. Gọi tên quá khứ rồi bước sang một đời mới.",
        "Tự phán xét nghiệt ngã, hoặc bỏ lỡ lời gọi đã vang.",
        "thức tỉnh, gọi tên",
        "tự kết, bỏ lỡ",
    ),
    (
        21,
        "The World",
        "Thế Giới",
        "Thế Giới",
        "Hoàn tất một vòng. Hòa hợp và cảm giác đã đến nơi.",
        "Dở dang, chưa khép, còn thiếu mảnh cuối của bức tranh.",
        "hoàn tất, hòa hợp",
        "dở dang, thiếu mảnh",
    ),
)

# (key, name_en, name_vi)
SUIT_META: tuple[tuple[str, str, str], ...] = (
    ("wands", "Wands", "Gậy"),
    ("cups", "Cups", "Cốc"),
    ("swords", "Swords", "Kiếm"),
    ("pentacles", "Pentacles", "Xu"),
)

# (number, name_en, name_vi, short_vi)
MINOR_RANKS: tuple[tuple[int, str, str, str], ...] = (
    (1, "Ace", "Át", "Át"),
    (2, "Two", "Hai", "2"),
    (3, "Three", "Ba", "3"),
    (4, "Four", "Bốn", "4"),
    (5, "Five", "Năm", "5"),
    (6, "Six", "Sáu", "6"),
    (7, "Seven", "Bảy", "7"),
    (8, "Eight", "Tám", "8"),
    (9, "Nine", "Chín", "9"),
    (10, "Ten", "Mười", "10"),
    (11, "Page", "Thị giả", "Thị giả"),
    (12, "Knight", "Hiệp sĩ", "Hiệp sĩ"),
    (13, "Queen", "Nữ hoàng", "Nữ hoàng"),
    (14, "King", "Đức vua", "Vua"),
)

# Per suit: 14 rows of (number, upright, reversed, kw_up, kw_rev)
SUIT_MEANINGS: dict[str, tuple[tuple[int, str, str, str, str], ...]] = {
    "wands": (
        (
            1,
            "Một tia lửa khởi sự. Ý tưởng muốn được làm thật.",
            "Cháy giả hoặc bắt đầu hụt; nhiệt đang có nhưng chưa thành đường.",
            "tia lửa, khởi sự",
            "hụt, cháy giả",
        ),
        (
            2,
            "Hoạch định và nhìn xa. Thế đứng trước khi bước.",
            "Sợ chọn, đứng chần chừ dù tầm nhìn đã có.",
            "kế hoạch, tầm nhìn",
            "do dự, đứng yên",
        ),
        (
            3,
            "Mở rộng, tàu ra khơi. Công sức bắt đầu có đất mới.",
            "Chậm trễ hoặc tầm nhìn bị thu hẹp giữa đường.",
            "mở rộng, ra khơi",
            "chậm, hẹp tầm",
        ),
        (
            4,
            "Ăn mừng, mái nhà, một chỗ được thở.",
            "Bất ổn trong tổ; bữa tiệc chưa tới hoặc vui không trọn.",
            "nhà, ăn mừng",
            "bất an, dở tiệc",
        ),
        (
            5,
            "Cạnh tranh, cọ xát. Va chạm để làm rõ ai đứng đâu.",
            "Né xung đột, hoặc căng thẳng ngầm đang mòn sức.",
            "cạnh tranh, cọ xát",
            "né, căng ngầm",
        ),
        (
            6,
            "Chiến thắng được công nhận. Người khác thấy nỗ lực của bạn.",
            "Chiến thắng hão hoặc danh tiếng rỗng; hãy kiểm lại thực chất.",
            "chiến thắng, ghi nhận",
            "hão, danh rỗng",
        ),
        (
            7,
            "Phòng thủ và giữ vị trí. Đứng vững khi bị thử.",
            "Quá tải, muốn buông. Thế phòng thủ đang ăn mòn.",
            "giữ vững, phòng thủ",
            "quá tải, muốn buông",
        ),
        (
            8,
            "Tăng tốc. Tin tức và chuyển động ập tới rất nhanh.",
            "Hỗn loạn tốc độ, hoặc tin đang bị trễ so với nhu cầu.",
            "tốc độ, tin tới",
            "hỗn, chậm tin",
        ),
        (
            9,
            "Bền bỉ. Gần xong, còn một nhịp chịu đựng nữa.",
            "Kiệt sức, phòng thủ thái quá, tưởng mọi thứ đều là đòn.",
            "bền bỉ, gần xong",
            "kiệt, phòng quá",
        ),
        (
            10,
            "Gánh trách nhiệm nặng. Vai đang đầy nhưng còn đi được.",
            "Chất thêm gánh không cần. Đến lúc đặt xuống một phần.",
            "gánh, trách nhiệm",
            "quá tải, buông bớt",
        ),
        (
            11,
            "Tin vui, tò mò, một sứ giả của lửa.",
            "Tin thất hoặc thiếu tập trung; ngọn lửa chưa có nơi đặt.",
            "tin vui, tò mò",
            "tin thất, phân tán",
        ),
        (
            12,
            "Lao tới với nhiệt. Hành động dứt khoát, không chờ hoàn hảo.",
            "Hấp tấp, cháy nhà vì đi quá nhanh so với bản đồ.",
            "xông tới, nhiệt",
            "hấp tấp, cháy",
        ),
        (
            13,
            "Tự tin, truyền lửa cho người khác. Sức nóng có chủ.",
            "Ghen hoặc muốn kiểm soát ngọn lửa của người khác.",
            "tự tin, truyền lửa",
            "ghen, kiểm soát",
        ),
        (
            14,
            "Lãnh đạo bằng tầm nhìn. Biết khi nào đốt và khi nào giữ than.",
            "Độc đoán, bạo khí; lửa lãnh đạo thành lửa thiêu.",
            "tầm nhìn, lãnh đạo",
            "độc đoán, bạo",
        ),
    ),
    "cups": (
        (
            1,
            "Trái tim mở. Một dòng cảm xúc mới muốn được đón.",
            "Chặn cảm xúc, hoặc tình cảm đang được diễn hơn là được sống.",
            "trái tim, nguồn",
            "chặn, giả cảm",
        ),
        (
            2,
            "Kết nối đôi, hòa hợp. Hai chén cùng một nhịp.",
            "Lệch nhịp, chia xa, hoặc gắn kết chỉ còn hình thức.",
            "đôi, hòa hợp",
            "lệch, chia",
        ),
        (
            3,
            "Bạn bè, nâng ly, niềm vui được chia.",
            "Ngồi ngoài vòng vui, hoặc niềm vui nông không nuôi được.",
            "bạn bè, nâng ly",
            "ngoài cuộc, nông",
        ),
        (
            4,
            "Chán và bỏ lỡ. Chén mới đưa tới mà mắt còn nhìn chỗ cũ.",
            "Tỉnh lại, nhìn thấy cơ hội từng bị phớt lờ.",
            "chán, bỏ lỡ",
            "tỉnh, thấy lại",
        ),
        (
            5,
            "Mất mát. Ba chén đổ, nhưng còn hai chén đứng sau lưng.",
            "Bắt đầu chấp nhận. Quay lại với phần chưa mất.",
            "mất mát, tiếc",
            "chấp nhận, còn lại",
        ),
        (
            6,
            "Hoài niệm, thuở nhỏ, món quà từ quá khứ.",
            "Kẹt trong ngày xưa, hoặc nhớ một phiên bản đã được chỉnh.",
            "hoài niệm, cũ",
            "kẹt quá khứ",
        ),
        (
            7,
            "Nhiều mơ, nhiều lựa chọn. Ảo ảnh cũng nằm trong số đó.",
            "Tỉnh mộng và chọn thứ có thể cầm được.",
            "mơ, lựa chọn",
            "tỉnh, chọn thật",
        ),
        (
            8,
            "Bỏ đi để tìm tầng sâu hơn. Chén đầy vẫn có thể không đủ.",
            "Sợ rời, dở dang; chân muốn đi mà tay còn giữ.",
            "rời, tìm sâu",
            "sợ rời, dở",
        ),
        (
            9,
            "Toại nguyện. Điều ước thành, được phép hưởng.",
            "Thỏa mãn rỗng, kiêu; có đủ thứ mà vẫn đói.",
            "toại nguyện, ước",
            "rỗng, kiêu",
        ),
        (
            10,
            "Gia đình, viên mãn, một mái ấm đúng nghĩa.",
            "Rạn trong nhà, hạnh phúc bề mặt, thiếu sự thật dưới tiệc.",
            "gia đình, viên mãn",
            "rạn, bề mặt",
        ),
        (
            11,
            "Tin cảm xúc, tâm thơ, lời mời của tim.",
            "Nhạy quá mức, tin thất, cảm xúc chưa lọc.",
            "tin cảm, thơ",
            "nhạy, tin thất",
        ),
        (
            12,
            "Lời mời lãng mạn, đi theo thủy triều của tim.",
            "Hứa suông, thất thường; con ngựa cảm xúc không có dây cương.",
            "lãng mạn, lời mời",
            "hứa suông, thất thường",
        ),
        (
            13,
            "Đồng cảm, trực giác, biết đọc nước mà không chìm.",
            "Hút cảm xúc người khác đến kiệt, mất bờ của mình.",
            "đồng cảm, nước",
            "hút cạn, mất bờ",
        ),
        (
            14,
            "Chín chắn cảm xúc. Giữ được chén mà không tràn.",
            "Lạnh, kìm nén; trưởng thành thành cái vỏ không còn nước.",
            "chín chắn, giữ",
            "lạnh, kìm",
        ),
    ),
    "swords": (
        (
            1,
            "Sự thật sắc và một ý tưởng mới. Lời nói có thể cắt nút thắt.",
            "Lời làm đau, hoặc ý tưởng còn chưa rõ đã bị vung ra.",
            "sự thật, ý mới",
            "lời đau, mơ hồ",
        ),
        (
            2,
            "Thế bế, nhắm mắt giữa hai lưỡi. Cần một quyết định.",
            "Mở mắt và chọn. Tránh né không còn là lựa chọn.",
            "bế tắc, cân",
            "chọn, đối diện",
        ),
        (
            3,
            "Đau tim. Lời và sự thật cắt vào chỗ mềm.",
            "Lành dần, rút lời, hoặc nỗi đau bắt đầu có tên để chữa.",
            "đau, cắt",
            "lành, gọi tên",
        ),
        (
            4,
            "Nghỉ để phục hồi. Gác kiếm trước khi gãy.",
            "Trì trệ, trốn trong nghỉ ngơi vì sợ trận tiếp theo.",
            "nghỉ, phục hồi",
            "trì, trốn",
        ),
        (
            5,
            "Thắng nhưng mất. Ego đứng trên sân mà không còn đồng minh.",
            "Hòa và buông cuộc. Không phải trận nào cũng cần thắng.",
            "thắng rỗng, ego",
            "hòa, buông",
        ),
        (
            6,
            "Rời vùng bão. Chuyển chỗ để đầu được yên.",
            "Kẹt lại, chưa đi dù thuyền đã sẵn.",
            "rời bão, chuyển",
            "kẹt, chưa đi",
        ),
        (
            7,
            "Chiến lược, đi đường tắt, lấy bằng trí chứ không bằng lực.",
            "Bị bắt hoặc tự lừa. Đường tắt hóa thành cái bẫy.",
            "chiến lược, lén",
            "bị bắt, tự lừa",
        ),
        (
            8,
            "Kẹt và tự trói. Nhiều sợi dây là do mình quấn.",
            "Thấy lối thoát. Cởi được nút từng nghĩ là nhà tù.",
            "kẹt, tự trói",
            "thấy lối, cởi",
        ),
        (
            9,
            "Lo đêm, vòng xoáy trong đầu. Nỗi sợ lớn hơn sự thật.",
            "Ánh sáng lọt vào. Lo lắng tan khi được nói ra.",
            "lo âu, đêm",
            "tan lo, nói ra",
        ),
        (
            10,
            "Đáy. Một kết thúc đau nhưng cũng là điểm không thể thấp hơn.",
            "Bình minh sau đáy. Điều tồi nhất đã qua.",
            "đáy, kết đau",
            "bình minh, qua cơn",
        ),
        (
            11,
            "Tò mò trí tuệ, tin tức, hỏi để hiểu.",
            "Tin độc, nói thiếu nghĩ; lưỡi kiếm của người chưa học đủ.",
            "tò mò, tin",
            "tin độc, thiếu nghĩ",
        ),
        (
            12,
            "Lao vào tranh bằng lý. Nhanh, sắc, không chờ được mời.",
            "Càn quét. Lời như kiếm, thắng cuộc mà mất người.",
            "sắc, xông vào",
            "càn, lời độc",
        ),
        (
            13,
            "Rõ ràng và độc lập. Nhìn thẳng, nói thẳng, không vòng.",
            "Lạnh lùng, lời cắt. Sự thật không cần được dùng như vũ khí.",
            "rõ, độc lập",
            "lạnh, lời cắt",
        ),
        (
            14,
            "Trí tuệ và công lý trong lời. Phán với cái đầu lạnh.",
            "Độc tài lý lẽ, tàn nhẫn. Đúng mà không còn nhân.",
            "trí tuệ, công lý",
            "độc tài, tàn",
        ),
    ),
    "pentacles": (
        (
            1,
            "Hạt giống vật chất. Một cơ hội cầm được bằng tay.",
            "Cơ hội trễ, hoặc đang đo giá trị bằng thước lệch.",
            "hạt giống, cơ hội",
            "trễ, lệch giá",
        ),
        (
            2,
            "Cân bằng và xoay sở. Giữ nhịp giữa nhiều việc.",
            "Rối, mất nhịp, bóng đang rơi vì bắt quá nhiều.",
            "cân bằng, xoay",
            "rối, mất nhịp",
        ),
        (
            3,
            "Học nghề, cộng tác, làm ra thứ có thể dùng.",
            "Cắt góc, làm ẩu; sản phẩm chưa xứng công.",
            "nghề, cộng tác",
            "ẩu, cắt góc",
        ),
        (
            4,
            "Giữ của và an toàn. Biết nắm để không mất.",
            "Keo kiệt, sợ mất đến mức không dám sống với những gì đang có.",
            "giữ, an toàn",
            "keo, sợ mất",
        ),
        (
            5,
            "Thiếu thốn, đứng ngoài cửa ấm. Cần giúp và cần dám xin.",
            "Giúp đang tới, hoặc bạn chưa chịu với tay.",
            "thiếu, ngoài cửa",
            "cứu trợ, với tay",
        ),
        (
            6,
            "Cho và nhận. Hào phóng đúng lúc làm cả hai phía nhẹ.",
            "Cho để kiểm soát, sợi dây buộc trong món quà.",
            "cho nhận, hào phóng",
            "dây buộc, kiểm soát",
        ),
        (
            7,
            "Chờ mùa. Kiên nhẫn với thứ đang lớn dưới đất.",
            "Nản, muốn gặt sớm. Đừng nhổ mầm vì chưa thấy quả.",
            "chờ mùa, kiên nhẫn",
            "nản, gặt sớm",
        ),
        (
            8,
            "Rèn nghề, chăm chỉ. Tay làm ra sự chắc.",
            "Cầu toàn thành máy móc; làm mãi mà không còn yêu việc.",
            "rèn, chăm",
            "cầu toàn, máy móc",
        ),
        (
            9,
            "Tự chủ, hưởng quả của mình. Đủ để đứng một mình.",
            "Khoe của, hoặc cô độc vì lấy vật chất làm tường.",
            "tự chủ, hưởng",
            "khoe, cô độc",
        ),
        (
            10,
            "Gia sản, di sản, một hệ thống nuôi được nhiều đời.",
            "Gia tộc căng, của cải chia; nhà giàu mà không ấm.",
            "di sản, nhà",
            "chia, căng tộc",
        ),
        (
            11,
            "Học tiền bạc và thực tế. Bước đầu của sự chắc.",
            "Lười hoặc để cơ hội trôi vì chưa muốn lớn.",
            "học, thực tế",
            "lười, trôi mất",
        ),
        (
            12,
            "Tiến đều, đáng tin. Con ngựa đất không cần phi để tới.",
            "Chậm quá thành cứng; ổn định hóa ra đứng im.",
            "đều, đáng tin",
            "chậm, cứng",
        ),
        (
            13,
            "Nuôi dưỡng thực tế, chăm nhà, làm đất màu.",
            "Lo vật chất thái quá, quên thứ đất không mua được.",
            "chăm, nuôi đất",
            "lo của, quên hồn",
        ),
        (
            14,
            "Vững và biết quản. Vua của những thứ cầm được.",
            "Bám địa vị, khô khan; chắc nhưng không còn sống.",
            "vững, quản trị",
            "bám vị, khô",
        ),
    ),
}
